version: '3.9'

services:
  database:
    container_name: postgresql
    image: postgres:16rc1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infosena
    ports:
      - "5500:5432"
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isreasy -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - database_infosena:/var/lib/postgresql/data
      
volumes:
  database_infosena:
    name: database_infosena
